### Tensors in PyTorch

In [1]:
import torch

In [2]:
def activation(x):
    return 1 / (1 + torch.exp(-x))

In [18]:
# Generate some data
torch.manual_seed(7)   # Set the random seed so thinhs are predictable

# Features are 5 random normal variables
features = torch.randn((1, 5))    # tensor with shape(1, 5)

# True weigths for our data
weights = torch.randn_like(features)    # create Same shape as features

# True bais term
bias = torch.randn((1, 1))

There are a few options here: [`weights.reshape()`](https://pytorch.org/docs/stable/tensors.html#torch.Tensor.reshape), [`weights.resize_()`](https://pytorch.org/docs/stable/tensors.html#torch.Tensor.resize_), and [`weights.view()`](https://pytorch.org/docs/stable/tensors.html#torch.Tensor.view).

* `weights.reshape(a, b)` will return a new tensor with the same data as `weights` with size `(a, b)` sometimes, and sometimes a clone, as in it copies the data to another part of memory.
* `weights.resize_(a, b)` returns the same tensor with a different shape. However, if the new shape results in fewer elements than the original tensor, some elements will be removed from the tensor (but not from memory). If the new shape results in more elements than the original tensor, new elements will be uninitialized in memory. Here I should note that the underscore at the end of the method denotes that this method is performed **in-place**. Here is a great forum thread to [read more about in-place operations](https://discuss.pytorch.org/t/what-is-in-place-operation/16244) in PyTorch.
* `weights.view(a, b)` will return a new tensor with the same data as `weights` with size `(a, b)`.

I usually use `.view()`, but any of the three methods will work for this. So, now we can reshape `weights` to have five rows and one column with something like `weights.view(5, 1)`.

In [20]:
## Calculate the output of this network using the weights and bias tensors
y = activation(torch.sum(features * weights) + bias)
y

tensor([[0.1595]])

In [21]:
# Calculate the output of our little network using matrix multiplication
y = activation(torch.mm(features, weights.view(5, 1)) + bias)
y

tensor([[0.1595]])

#### Stacking layers up

In [23]:
 # Generate some data
torch.manual_seed(7)

# features
features = torch.randn((1, 3))

# Define the size of each layer in network
n_input = features.shape[1]
n_hidden = 2
n_output = 1

# Weigths for inputs to hidden layer
W1 = torch.randn((n_input, n_hidden))

# Weigths for hidden layer to output
W2 = torch.randn((n_hidden, n_output))

# Bias terms for hidden and output layers
B1 = torch.randn((1, n_hidden))
B2 = torch.randn((1, n_output))

In [25]:
# Calculate the output for this multi-layer network using the weights W1 & W2, 
# and the biases, B1 & B2.
h = activation(torch.mm(features, W1) + B1)
output = activation(torch.mm(h, W2) + B2)
output

tensor([[0.3171]])

#### Numpy to Torch and back

Special bonus section! PyTorch has a great feature for converting between Numpy arrays and Torch tensors. To create a tensor from a Numpy array, use `torch.from_numpy()`. To convert a tensor to a Numpy array, use the `.numpy()` method.

In [27]:
import numpy as np
np.set_printoptions(precision=8)

In [28]:
a = np.random.rand(4, 3)
a

array([[0.90299678, 0.79977705, 0.44868128],
       [0.09453628, 0.93396927, 0.13715425],
       [0.69372288, 0.20603646, 0.60266692],
       [0.85678654, 0.70470149, 0.15686255]])

In [29]:
torch.set_printoptions(precision=8)
b = torch.from_numpy(a)
b

tensor([[0.90299678, 0.79977705, 0.44868128],
        [0.09453628, 0.93396927, 0.13715425],
        [0.69372288, 0.20603646, 0.60266692],
        [0.85678654, 0.70470149, 0.15686255]], dtype=torch.float64)

In [30]:
b.numpy()

array([[0.90299678, 0.79977705, 0.44868128],
       [0.09453628, 0.93396927, 0.13715425],
       [0.69372288, 0.20603646, 0.60266692],
       [0.85678654, 0.70470149, 0.15686255]])

The memory is shared between the Numpy array and Torch tensor, so if you change the values in-place of one object, the other will change as well.

In [31]:
b.mul_(2)

tensor([[1.80599356, 1.59955409, 0.89736256],
        [0.18907255, 1.86793855, 0.27430851],
        [1.38744576, 0.41207292, 1.20533384],
        [1.71357308, 1.40940297, 0.31372510]], dtype=torch.float64)

In [32]:
a

array([[1.80599356, 1.59955409, 0.89736256],
       [0.18907255, 1.86793855, 0.27430851],
       [1.38744576, 0.41207292, 1.20533384],
       [1.71357308, 1.40940297, 0.3137251 ]])